// <auto-generated />
using System;
using JasperGreen.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JasperGreen.Migrations
{
    [DbContext(typeof(JasperGreenDbContext))]
    partial class JasperGreenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JasperGreen.Models.Crew", b =>
                {
                    b.Property<int>("Crew_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Crew_ID"));

                    b.Property<int>("Crew_Foreman")
                        .HasColumnType("int");

                    b.Property<int>("Crew_Member_1")
                        .HasColumnType("int");

                    b.Property<int>("Crew_Member_2")
                        .HasColumnType("int");

                    b.HasKey("Crew_ID");

                    b.HasIndex("Crew_Foreman");

                    b.HasIndex("Crew_Member_1");

                    b.HasIndex("Crew_Member_2");

                    b.ToTable("Crews");

                    b.HasData(
                        new
                        {
                            Crew_ID = 1,
                            Crew_Foreman = 2,
                            Crew_Member_1 = 5,
                            Crew_Member_2 = 4
                        },
                        new
                        {
                            Crew_ID = 2,
                            Crew_Foreman = 3,
                            Crew_Member_1 = 6,
                            Crew_Member_2 = 7
                        },
                        new
                        {
                            Crew_ID = 3,
                            Crew_Foreman = 8,
                            Crew_Member_1 = 9,
                            Crew_Member_2 = 10
                        });
                });

            modelBuilder.Entity("JasperGreen.Models.Customer", b =>
                {
                    b.Property<int>("Cust_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cust_ID"));

                    b.Property<string>("Cust_Billing_Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cust_Billing_City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cust_Billing_State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cust_Billing_Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cust_Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cust_Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Cust_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cust_ID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Cust_ID = 1,
                            Cust_Billing_Address = "101 Fairway Dr",
                            Cust_Billing_City = "Dallas",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "75201",
                            Cust_Email = "jspieth@email.com",
                            Cust_Name = "Jordan Spieth",
                            Cust_Phone = "2145551001"
                        },
                        new
                        {
                            Cust_ID = 2,
                            Cust_Billing_Address = "202 Masters Ln",
                            Cust_Billing_City = "Dallas",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "75202",
                            Cust_Email = "sscheffler@email.com",
                            Cust_Name = "Scottie Scheffler",
                            Cust_Phone = "2145551002"
                        },
                        new
                        {
                            Cust_ID = 3,
                            Cust_Billing_Address = "303 Augusta Way",
                            Cust_Billing_City = "Plano",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "75023",
                            Cust_Email = "wzalatoris@email.com",
                            Cust_Name = "Will Zalatoris",
                            Cust_Phone = "9725551003"
                        },
                        new
                        {
                            Cust_ID = 4,
                            Cust_Billing_Address = "404 Eagle Bend",
                            Cust_Billing_City = "Houston",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "77002",
                            Cust_Email = "tfinau@email.com",
                            Cust_Name = "Tony Finau",
                            Cust_Phone = "7135551004"
                        },
                        new
                        {
                            Cust_ID = 5,
                            Cust_Billing_Address = "505 Greenview Ct",
                            Cust_Billing_City = "Austin",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "73301",
                            Cust_Email = "bdechambeau@email.com",
                            Cust_Name = "Bryson DeChambeau",
                            Cust_Phone = "5125551005"
                        },
                        new
                        {
                            Cust_ID = 6,
                            Cust_Billing_Address = "606 Pinehurst Dr",
                            Cust_Billing_City = "Frisco",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "75034",
                            Cust_Email = "mhoma@email.com",
                            Cust_Name = "Max Homa",
                            Cust_Phone = "4695551006"
                        },
                        new
                        {
                            Cust_ID = 7,
                            Cust_Billing_Address = "707 Clubhouse Blvd",
                            Cust_Billing_City = "Fort Worth",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "76102",
                            Cust_Email = "cmorikawa@email.com",
                            Cust_Name = "Collin Morikawa",
                            Cust_Phone = "8175551007"
                        },
                        new
                        {
                            Cust_ID = 8,
                            Cust_Billing_Address = "808 Pebble Beach Rd",
                            Cust_Billing_City = "San Antonio",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "78205",
                            Cust_Email = "xschauffele@email.com",
                            Cust_Name = "Xander Schauffele",
                            Cust_Phone = "2105551008"
                        },
                        new
                        {
                            Cust_ID = 9,
                            Cust_Billing_Address = "909 Open Championship Way",
                            Cust_Billing_City = "Bryan",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "77802",
                            Cust_Email = "jthomas@email.com",
                            Cust_Name = "Justin Thomas",
                            Cust_Phone = "9795551009"
                        },
                        new
                        {
                            Cust_ID = 10,
                            Cust_Billing_Address = "1001 Players Club Dr",
                            Cust_Billing_City = "College Station",
                            Cust_Billing_State = "TX",
                            Cust_Billing_Zip = "77840",
                            Cust_Email = "rfowler@email.com",
                            Cust_Name = "Rickie Fowler",
                            Cust_Phone = "9795551010"
                        });
                });

            modelBuilder.Entity("JasperGreen.Models.Employee", b =>
                {
                    b.Property<int>("Emp_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Emp_ID"));

                    b.Property<string>("Emp_First_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Emp_Hire_Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Emp_Hourly_Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Emp_Job_Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Emp_Last_Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Emp_SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_ID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Emp_ID = 1,
                            Emp_First_Name = "Cole",
                            Emp_Hire_Date = new DateOnly(2019, 3, 15),
                            Emp_Hourly_Rate = 26.50m,
                            Emp_Job_Title = "Owner",
                            Emp_Last_Name = "Howell",
                            Emp_SSN = "123456789"
                        },
                        new
                        {
                            Emp_ID = 2,
                            Emp_First_Name = "Chris",
                            Emp_Hire_Date = new DateOnly(2022, 5, 10),
                            Emp_Hourly_Rate = 18.75m,
                            Emp_Job_Title = "Crew",
                            Emp_Last_Name = "Lopez",
                            Emp_SSN = "987654321"
                        },
                        new
                        {
                            Emp_ID = 3,
                            Emp_First_Name = "Aaron",
                            Emp_Hire_Date = new DateOnly(2023, 2, 20),
                            Emp_Hourly_Rate = 19.25m,
                            Emp_Job_Title = "Crew",
                            Emp_Last_Name = "White",
                            Emp_SSN = "111223333"
                        },
                        new
                        {
                            Emp_ID = 4,
                            Emp_First_Name = "Brian",
                            Emp_Hire_Date = new DateOnly(2020, 8, 12),
                            Emp_Hourly_Rate = 27.00m,
                            Emp_Job_Title = "Foreman",
                            Emp_Last_Name = "Hall",
                            Emp_SSN = "222334444"
                        },
                        new
                        {
                            Emp_ID = 5,
                            Emp_First_Name = "Kevin",
                            Emp_Hire_Date = new DateOnly(2021, 11, 5),
                            Emp_Hourly_Rate = 18.50m,
                            Emp_Job_Title = "Crew",
                            Emp_Last_Name = "Young",
                            Emp_SSN = "333445555"
                        },
                        new
                        {
                            Emp_ID = 6,
                            Emp_First_Name = "Daniel",
                            Emp_Hire_Date = new DateOnly(2022, 7, 18),
                            Emp_Hourly_Rate = 19.00m,
                            Emp_Job_Title = "Crew",
                            Emp_Last_Name = "King",
                            Emp_SSN = "444556666"
                        },
                        new
                        {
                            Emp_ID = 7,
                            Emp_First_Name = "Jason",
                            Emp_Hire_Date = new DateOnly(2019, 4, 22),
                            Emp_Hourly_Rate = 28.25m,
                            Emp_Job_Title = "Foreman",
                            Emp_Last_Name = "Scott",
                            Emp_SSN = "555667777"
                        },
                        new
                        {
                            Emp_ID = 8,
                            Emp_First_Name = "Mark",
                            Emp_Hire_Date = new DateOnly(2023, 1, 9),
                            Emp_Hourly_Rate = 18.90m,
                            Emp_Job_Title = "Crew",
                            Emp_Last_Name = "Green",
                            Emp_SSN = "666778888"
                        },
                        new
                        {
                            Emp_ID = 9,
                            Emp_First_Name = "Ryan",
                            Emp_Hire_Date = new DateOnly(2020, 10, 14),
                            Emp_Hourly_Rate = 19.10m,
                            Emp_Job_Title = "Crew",
                            Emp_Last_Name = "Baker",
                            Emp_SSN = "777889999"
                        },
                        new
                        {
                            Emp_ID = 10,
                            Emp_First_Name = "Eric",
                            Emp_Hire_Date = new DateOnly(2021, 6, 30),
                            Emp_Hourly_Rate = 18.65m,
                            Emp_Job_Title = "Crew",
                            Emp_Last_Name = "Adams",
                            Emp_SSN = "888990000"
                        });
                });

            modelBuilder.Entity("JasperGreen.Models.Payment", b =>
                {
                    b.Property<int>("Payment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Payment_ID"));

                    b.Property<decimal>("Payment_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Payment_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Service_ID")
                        .HasColumnType("int");

                    b.HasKey("Payment_ID");

                    b.HasIndex("Service_ID")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Payment_ID = 1,
                            Payment_Amount = 65.00m,
                            Payment_Date = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 1
                        },
                        new
                        {
                            Payment_ID = 2,
                            Payment_Amount = 85.00m,
                            Payment_Date = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Check",
                            Service_ID = 2
                        },
                        new
                        {
                            Payment_ID = 3,
                            Payment_Amount = 65.00m,
                            Payment_Date = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 3
                        },
                        new
                        {
                            Payment_ID = 4,
                            Payment_Amount = 95.00m,
                            Payment_Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 5
                        },
                        new
                        {
                            Payment_ID = 5,
                            Payment_Amount = 120.00m,
                            Payment_Date = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Check",
                            Service_ID = 6
                        },
                        new
                        {
                            Payment_ID = 6,
                            Payment_Amount = 95.00m,
                            Payment_Date = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 7
                        },
                        new
                        {
                            Payment_ID = 7,
                            Payment_Amount = 75.00m,
                            Payment_Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Cash",
                            Service_ID = 9
                        },
                        new
                        {
                            Payment_ID = 8,
                            Payment_Amount = 75.00m,
                            Payment_Date = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 10
                        },
                        new
                        {
                            Payment_ID = 9,
                            Payment_Amount = 80.00m,
                            Payment_Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Check",
                            Service_ID = 12
                        },
                        new
                        {
                            Payment_ID = 10,
                            Payment_Amount = 80.00m,
                            Payment_Date = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 13
                        },
                        new
                        {
                            Payment_ID = 11,
                            Payment_Amount = 90.00m,
                            Payment_Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 15
                        },
                        new
                        {
                            Payment_ID = 12,
                            Payment_Amount = 90.00m,
                            Payment_Date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Cash",
                            Service_ID = 16
                        },
                        new
                        {
                            Payment_ID = 13,
                            Payment_Amount = 85.00m,
                            Payment_Date = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Check",
                            Service_ID = 18
                        },
                        new
                        {
                            Payment_ID = 14,
                            Payment_Amount = 85.00m,
                            Payment_Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 19
                        },
                        new
                        {
                            Payment_ID = 15,
                            Payment_Amount = 100.00m,
                            Payment_Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 21
                        },
                        new
                        {
                            Payment_ID = 16,
                            Payment_Amount = 100.00m,
                            Payment_Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Check",
                            Service_ID = 22
                        },
                        new
                        {
                            Payment_ID = 17,
                            Payment_Amount = 95.00m,
                            Payment_Date = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 24
                        },
                        new
                        {
                            Payment_ID = 18,
                            Payment_Amount = 95.00m,
                            Payment_Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Cash",
                            Service_ID = 25
                        },
                        new
                        {
                            Payment_ID = 19,
                            Payment_Amount = 70.00m,
                            Payment_Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Check",
                            Service_ID = 27
                        },
                        new
                        {
                            Payment_ID = 20,
                            Payment_Amount = 70.00m,
                            Payment_Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Card",
                            Service_ID = 28
                        },
                        new
                        {
                            Payment_ID = 21,
                            Payment_Amount = 75.00m,
                            Payment_Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Cash",
                            Service_ID = 30
                        },
                        new
                        {
                            Payment_ID = 22,
                            Payment_Amount = 75.00m,
                            Payment_Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Payment_Method = "Check",
                            Service_ID = 31
                        });
                });

            modelBuilder.Entity("JasperGreen.Models.Property", b =>
                {
                    b.Property<int>("Property_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Property_ID"));

                    b.Property<int>("Cust_ID")
                        .HasColumnType("int");

                    b.Property<string>("Property_Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Property_City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Property_Service_Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Property_State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Property_ZIP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Property_ID");

                    b.HasIndex("Cust_ID");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Property_ID = 1,
                            Cust_ID = 1,
                            Property_Address = "101 Fairway Dr",
                            Property_City = "Dallas",
                            Property_Service_Fee = 65.00m,
                            Property_State = "TX",
                            Property_ZIP = "75201"
                        },
                        new
                        {
                            Property_ID = 2,
                            Cust_ID = 1,
                            Property_Address = "102 Fairway Dr",
                            Property_City = "Dallas",
                            Property_Service_Fee = 85.00m,
                            Property_State = "TX",
                            Property_ZIP = "75201"
                        },
                        new
                        {
                            Property_ID = 3,
                            Cust_ID = 2,
                            Property_Address = "202 Masters Ln",
                            Property_City = "Dallas",
                            Property_Service_Fee = 95.00m,
                            Property_State = "TX",
                            Property_ZIP = "75202"
                        },
                        new
                        {
                            Property_ID = 4,
                            Cust_ID = 2,
                            Property_Address = "203 Masters Ln",
                            Property_City = "Dallas",
                            Property_Service_Fee = 120.00m,
                            Property_State = "TX",
                            Property_ZIP = "75202"
                        },
                        new
                        {
                            Property_ID = 5,
                            Cust_ID = 3,
                            Property_Address = "303 Augusta Way",
                            Property_City = "Plano",
                            Property_Service_Fee = 75.00m,
                            Property_State = "TX",
                            Property_ZIP = "75023"
                        },
                        new
                        {
                            Property_ID = 6,
                            Cust_ID = 4,
                            Property_Address = "404 Eagle Bend",
                            Property_City = "Houston",
                            Property_Service_Fee = 80.00m,
                            Property_State = "TX",
                            Property_ZIP = "77002"
                        },
                        new
                        {
                            Property_ID = 7,
                            Cust_ID = 5,
                            Property_Address = "505 Greenview Ct",
                            Property_City = "Austin",
                            Property_Service_Fee = 90.00m,
                            Property_State = "TX",
                            Property_ZIP = "73301"
                        },
                        new
                        {
                            Property_ID = 8,
                            Cust_ID = 6,
                            Property_Address = "606 Pinehurst Dr",
                            Property_City = "Frisco",
                            Property_Service_Fee = 85.00m,
                            Property_State = "TX",
                            Property_ZIP = "75034"
                        },
                        new
                        {
                            Property_ID = 9,
                            Cust_ID = 7,
                            Property_Address = "707 Clubhouse Blvd",
                            Property_City = "Fort Worth",
                            Property_Service_Fee = 100.00m,
                            Property_State = "TX",
                            Property_ZIP = "76102"
                        },
                        new
                        {
                            Property_ID = 10,
                            Cust_ID = 8,
                            Property_Address = "808 Pebble Beach Rd",
                            Property_City = "San Antonio",
                            Property_Service_Fee = 95.00m,
                            Property_State = "TX",
                            Property_ZIP = "78205"
                        },
                        new
                        {
                            Property_ID = 11,
                            Cust_ID = 9,
                            Property_Address = "909 Open Championship Way",
                            Property_City = "Bryan",
                            Property_Service_Fee = 70.00m,
                            Property_State = "TX",
                            Property_ZIP = "77802"
                        },
                        new
                        {
                            Property_ID = 12,
                            Cust_ID = 10,
                            Property_Address = "1001 Players Club Dr",
                            Property_City = "College Station",
                            Property_Service_Fee = 75.00m,
                            Property_State = "TX",
                            Property_ZIP = "77840"
                        });
                });

            modelBuilder.Entity("JasperGreen.Models.Service", b =>
                {
                    b.Property<int>("Service_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Service_ID"));

                    b.Property<int>("Crew_ID")
                        .HasColumnType("int");

                    b.Property<int>("Cust_ID")
                        .HasColumnType("int");

                    b.Property<int>("Property_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Service_Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Service_Fee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Service_ID");

                    b.HasIndex("Crew_ID");

                    b.HasIndex("Cust_ID");

                    b.HasIndex("Property_ID");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Service_ID = 1,
                            Crew_ID = 1,
                            Cust_ID = 1,
                            Property_ID = 1,
                            Service_Date = new DateTime(2026, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 65.00m
                        },
                        new
                        {
                            Service_ID = 2,
                            Crew_ID = 1,
                            Cust_ID = 1,
                            Property_ID = 2,
                            Service_Date = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 85.00m
                        },
                        new
                        {
                            Service_ID = 3,
                            Crew_ID = 1,
                            Cust_ID = 1,
                            Property_ID = 1,
                            Service_Date = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 65.00m
                        },
                        new
                        {
                            Service_ID = 4,
                            Crew_ID = 1,
                            Cust_ID = 1,
                            Property_ID = 2,
                            Service_Date = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 85.00m
                        },
                        new
                        {
                            Service_ID = 5,
                            Crew_ID = 1,
                            Cust_ID = 2,
                            Property_ID = 3,
                            Service_Date = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 95.00m
                        },
                        new
                        {
                            Service_ID = 6,
                            Crew_ID = 1,
                            Cust_ID = 2,
                            Property_ID = 4,
                            Service_Date = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 120.00m
                        },
                        new
                        {
                            Service_ID = 7,
                            Crew_ID = 1,
                            Cust_ID = 2,
                            Property_ID = 3,
                            Service_Date = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 95.00m
                        },
                        new
                        {
                            Service_ID = 8,
                            Crew_ID = 1,
                            Cust_ID = 2,
                            Property_ID = 4,
                            Service_Date = new DateTime(2026, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 120.00m
                        },
                        new
                        {
                            Service_ID = 9,
                            Crew_ID = 2,
                            Cust_ID = 3,
                            Property_ID = 5,
                            Service_Date = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 75.00m
                        },
                        new
                        {
                            Service_ID = 10,
                            Crew_ID = 2,
                            Cust_ID = 3,
                            Property_ID = 5,
                            Service_Date = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 75.00m
                        },
                        new
                        {
                            Service_ID = 11,
                            Crew_ID = 2,
                            Cust_ID = 3,
                            Property_ID = 5,
                            Service_Date = new DateTime(2026, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 75.00m
                        },
                        new
                        {
                            Service_ID = 12,
                            Crew_ID = 2,
                            Cust_ID = 4,
                            Property_ID = 6,
                            Service_Date = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 80.00m
                        },
                        new
                        {
                            Service_ID = 13,
                            Crew_ID = 2,
                            Cust_ID = 4,
                            Property_ID = 6,
                            Service_Date = new DateTime(2026, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 80.00m
                        },
                        new
                        {
                            Service_ID = 14,
                            Crew_ID = 2,
                            Cust_ID = 4,
                            Property_ID = 6,
                            Service_Date = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 80.00m
                        },
                        new
                        {
                            Service_ID = 15,
                            Crew_ID = 2,
                            Cust_ID = 5,
                            Property_ID = 7,
                            Service_Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 90.00m
                        },
                        new
                        {
                            Service_ID = 16,
                            Crew_ID = 2,
                            Cust_ID = 5,
                            Property_ID = 7,
                            Service_Date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 90.00m
                        },
                        new
                        {
                            Service_ID = 17,
                            Crew_ID = 2,
                            Cust_ID = 5,
                            Property_ID = 7,
                            Service_Date = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 90.00m
                        },
                        new
                        {
                            Service_ID = 18,
                            Crew_ID = 3,
                            Cust_ID = 6,
                            Property_ID = 8,
                            Service_Date = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 85.00m
                        },
                        new
                        {
                            Service_ID = 19,
                            Crew_ID = 3,
                            Cust_ID = 6,
                            Property_ID = 8,
                            Service_Date = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 85.00m
                        },
                        new
                        {
                            Service_ID = 20,
                            Crew_ID = 3,
                            Cust_ID = 6,
                            Property_ID = 8,
                            Service_Date = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 85.00m
                        },
                        new
                        {
                            Service_ID = 21,
                            Crew_ID = 3,
                            Cust_ID = 7,
                            Property_ID = 9,
                            Service_Date = new DateTime(2026, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 100.00m
                        },
                        new
                        {
                            Service_ID = 22,
                            Crew_ID = 3,
                            Cust_ID = 7,
                            Property_ID = 9,
                            Service_Date = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 100.00m
                        },
                        new
                        {
                            Service_ID = 23,
                            Crew_ID = 3,
                            Cust_ID = 7,
                            Property_ID = 9,
                            Service_Date = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 100.00m
                        },
                        new
                        {
                            Service_ID = 24,
                            Crew_ID = 3,
                            Cust_ID = 8,
                            Property_ID = 10,
                            Service_Date = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 95.00m
                        },
                        new
                        {
                            Service_ID = 25,
                            Crew_ID = 3,
                            Cust_ID = 8,
                            Property_ID = 10,
                            Service_Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 95.00m
                        },
                        new
                        {
                            Service_ID = 26,
                            Crew_ID = 3,
                            Cust_ID = 8,
                            Property_ID = 10,
                            Service_Date = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 95.00m
                        },
                        new
                        {
                            Service_ID = 27,
                            Crew_ID = 1,
                            Cust_ID = 9,
                            Property_ID = 11,
                            Service_Date = new DateTime(2026, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 70.00m
                        },
                        new
                        {
                            Service_ID = 28,
                            Crew_ID = 1,
                            Cust_ID = 9,
                            Property_ID = 11,
                            Service_Date = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 70.00m
                        },
                        new
                        {
                            Service_ID = 29,
                            Crew_ID = 1,
                            Cust_ID = 9,
                            Property_ID = 11,
                            Service_Date = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 70.00m
                        },
                        new
                        {
                            Service_ID = 30,
                            Crew_ID = 2,
                            Cust_ID = 10,
                            Property_ID = 12,
                            Service_Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 75.00m
                        },
                        new
                        {
                            Service_ID = 31,
                            Crew_ID = 2,
                            Cust_ID = 10,
                            Property_ID = 12,
                            Service_Date = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 75.00m
                        },
                        new
                        {
                            Service_ID = 32,
                            Crew_ID = 2,
                            Cust_ID = 10,
                            Property_ID = 12,
                            Service_Date = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Service_Fee = 75.00m
                        });
                });

            modelBuilder.Entity("JasperGreen.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("JasperGreen.Models.Crew", b =>
                {
                    b.HasOne("JasperGreen.Models.Employee", "Foreman")
                        .WithMany()
                        .HasForeignKey("Crew_Foreman")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JasperGreen.Models.Employee", "CrewMember1")
                        .WithMany()
                        .HasForeignKey("Crew_Member_1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JasperGreen.Models.Employee", "CrewMember2")
                        .WithMany()
                        .HasForeignKey("Crew_Member_2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CrewMember1");

                    b.Navigation("CrewMember2");

                    b.Navigation("Foreman");
                });

            modelBuilder.Entity("JasperGreen.Models.Payment", b =>
                {
                    b.HasOne("JasperGreen.Models.Service", "Service")
                        .WithOne("Payment")
                        .HasForeignKey("JasperGreen.Models.Payment", "Service_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("JasperGreen.Models.Property", b =>
                {
                    b.HasOne("JasperGreen.Models.Customer", "Customer")
                        .WithMany("Properties")
                        .HasForeignKey("Cust_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("JasperGreen.Models.Service", b =>
                {
                    b.HasOne("JasperGreen.Models.Crew", "Crew")
                        .WithMany("Services")
                        .HasForeignKey("Crew_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JasperGreen.Models.Customer", "Customer")
                        .WithMany("Services")
                        .HasForeignKey("Cust_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JasperGreen.Models.Property", "Property")
                        .WithMany("Services")
                        .HasForeignKey("Property_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Crew");

                    b.Navigation("Customer");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JasperGreen.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JasperGreen.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JasperGreen.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JasperGreen.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JasperGreen.Models.Crew", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("JasperGreen.Models.Customer", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("JasperGreen.Models.Property", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("JasperGreen.Models.Service", b =>
                {
                    b.Navigation("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
